variables:
  IMAGE_TAG: "test_image"

stages:
  - build
  - test

image: docker:19.03.1
services:
  # To obtain a Docker daemon, request a Docker-in-Docker service
  - docker:19.03.1-dind

docker_build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo $CI_REGISTRY_USER $CI_REGISTRY_PASSWORD $CI_REGISTRY $CI_REGISTRY_IMAGE:$IMAGE_TAG
    - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG

docker_test:
  stage: test
  script:
    - docker info
    - docker build -t "$CI_REGISTRY_IMAGE" .
    - docker run -d "$CI_REGISTRY_IMAGE"
