stages:
  - build

image: docker:19.03.1
services:
  # To obtain a Docker daemon, request a Docker-in-Docker service
  - docker:19.03.1-dind

remote_job:
  stage: build
  script:
    - echo "This is code from the file, which is included from another repository"
